--- 
back: &id001 
  text: Belay
instructions: &id002 
  text: Instructions
  tip: Learn how t' play th' game
options: &id003 
  text: Riggin'
  tip: View an' change game settings
game: 
  title: "-=- Wrath: Appease or Die! -=- by Spooner -=-"
god: 
  ai: 
    name: SadOS
  azathoth: 
    name: Spawn o' Azathoth
  dryad: 
    name: Dryad
  earthquake: 
    name: Earthshaker
  mummy: 
    name: Muhazateptephotep
  squid: 
    name: Th' Kraken
  storm: 
    name: Poseidon
  volcano: 
    name: Th' Great Volcano
priest: 
  acolyte: 
    name: Acolyte
  chaplain: 
    name: Chaplain
  cutie: 
    name: Cutie
  druidess: 
    name: Druidess
  monk: 
    name: Monk
  nun: 
    name: Nun
  priestess: 
    name: Priestess
  prophet: 
    name: Prophet
  seer: 
    name: Seer
  shaman: 
    name: Shaman
  scientist: 
    name: Scientist
  thaumaturge: 
    name: Thaumaturge
  witch: 
    name: Witch
level: 
  cave: 
    name: Cave o' Considerable Doom
  desert: 
    name: Desert o' Dehydrated Doom
  facility: 
    name: D.O.O.M. Test Facility
  forest: 
    name: Forest o' Doom
  island: 
    name: Island o' Utter Doom
  moon: 
    name: Yuggoth
  ship: 
    name: Ship o' Doomed Fools
  undersea: 
    name: Davey Jones' Doom
gui: 
  view_achievements: 
    title: Deeds
    locked: Locked
    unlocked: Unlocked
    dialog: 
      confirm_reset: 
        message: Really delete all statistics, achivements an' unlocks?
    button: 
      back: *id001
      unlock: 
        text: Unlock all
        tip: Allow use o' all features, even if they be locked, until game be restarted
      reset: 
        text: Reset statistics
        tip: Resets all statistics, deeds an' unlocks PERMANENTLY
  game_menu: 
    button: 
      resume: 
        text: Resume
        tip: Resume playin' th' current game
      instructions: *id002
      options: *id003
      quit: 
        text: Quit
  host_details: 
    title: Hostin' a Game
    label: 
      player_name: Pirate name
      port: Port
    button: 
      back: *id001
      host: 
        text: Host
  instructions: 
    title: Instructions
    button: 
      back: *id001
    tab: 
      gods: 
        title: Th' Gods
        body: |
          * Gods be wrathful an' enjoy smitin' more than anythin' else (well, except seducin' mortals)!
          
          * Each map has a local deity that ye must appease, such as th' god o' earthquakes or storms.
          
          * Gods slowly become angry then they rain down disasters until they become bored (anger bar fills then empties).
          
          * As ye make sacrifices, it reduces th' anger o' th' god as well as givin' ye Holy Favour.
          
          * Th' god will ask for specific creatures, which will reap greater rewards when sacrificed.

      priests: 
        title: Buccaneers
        body: |
          * Each pirate picks one o' thirteen buccaneers. All buccaneers be identical in play, but some look cooler than others.
          
          * Yer buccaneer can pick up, use or throw objects or creatures. They do this with a single "action" key.
          
          * A buccaneer's current health be shown as a red bar next t' her portrait.
          
          * Dyin' will mean th' other pirate wins by default!

      favour: 
        title: Holy Favour
        body: |
          * Accumulate favour by makin' sacrifices at th' altar (buccaneers start standin' next t' th' altar).
          
          * Th' gods like animals, people an' treasures as sacrifices, but dislike mundane things, like rocks.
          
          * Creatures can be anointed at th' font t' give more favor when sacrificed.
          
          * Yer holy favour be shown as a white bar. Fill th' bar afor th' other buccaneer t' win!
          
          * Favour can also be used t' power magical items (e.g. magic carpets).

  join_details: 
    title: Joinin' a Game
    label: 
      player_name: Pirate name
      address: Host address
      port: Host port
    button: 
      back: *id001
      join: 
        text: Join
  lobby: 
    title: 
      host: Host lobby
      client: Client lobby
      offline: Lobby
    button: 
      back: *id001
      ready: 
        text: Ready
      start: 
        text: Start
    label: 
      god: God
      map: Map
      ready: Ready
      wait_for_start: Wait for host t' start game
  menu: 
    title: Wrath
    subtitle: Appease or Die!
    label: 
      version: v%1 by Spooner
    button: 
      play: 
        text: Play
        tip: Play th' game, on- or off-line
      instructions: *id002
      achievements: 
        text: Deeds
        tip: Review yer deeds
      options: *id003
      exit: 
        text: Exit
        tip: Leave game
  options: 
    title: Riggin'
    dialog: 
      confirm_default: 
        message: Really reset all riggin' (audio, video an' controls) t' their default values?
    button: 
      back: *id001
      audio: 
        text: Audio
      video: 
        text: Video
      controls: 
        text: Controls
      general: 
        text: General
      default: 
        text: Default all riggin'
        tip: Reset all riggin' (audio, video an' controls) t' their default values
  options_audio: 
    title: Riggin' | Audio
    dialog: 
      confirm_default: 
        message: Really set all volumes t' default values an' remove mutin'?
    label: 
      master: Master
      effects: Effects
      music: Music
    button: 
      back: *id001
      mute: 
        text: Mute
      play_sample: 
        text: Play
      default: 
        text: Defaults
        tip: Reset volumes t' default values an' remove mutin'
  options_general: 
    title: Riggin' | General
    default_locale: Default
    label: 
      locale: Locale
      warning: Changes require that th' game be restarted
    button: 
      back: *id001
  options_video: 
    title: Riggin' | Video
    zoom: (X%1 zoom)
    dialog: 
      confirm_default: 
        message: Really run th' game in a window at th' default size?
    label: 
      warning: Changes require that th' game be restarted
    button: 
      back: *id001
      windowed: 
        text: Windowed
        tip: Run th' game in a window
      full_screen: 
        text: Full-screen
        tip: Run th' game in a full screen at desktop resolution
      default: 
        text: Defaults
        tip: Reset t' default values
      exit: 
        text: Exit
  options_controls: 
    title: Riggin' | Controls
    dialog: 
      confirm_default: 
        message: Really default all controls?
    label: 
      up: Up
      down: Down
      left: Left
      right: Right
      action: Action
      toggle_network: Network stats (online)
      toggle_fps: FPS
      chat: Chat (online)
      menu: Menu
    button: 
      back: *id001
      default: 
        text: Defaults
        tip: Reset all controls t' their default values
    tab: 
      offline_player_1: 
        text: Pirate 1
        tip: Controls for pirate 1 (left side) when sharin' th' keyboard
      offline_player_2: 
        text: Pirate 2
        tip: Controls for pirate 2 (right side) when sharin' th' keyboard
      online_player: 
        text: Online pirate
        tip: Controls for th' pirate in a network game
      general: 
        text: General
        tip: General controls, such as diplayin' FPS or chattin' in network play.
  play: 
    title: Play Wrath
    button: 
      back: *id001
      offline: 
        text: Offline game
        tip: Both pirates on th' same keyboard
      join: 
        text: Join Game
        tip: Connect t' a network game someone else be hostin'
      host: 
        text: Host Game
        tip: Host a network game that another pirate can join
  game_over: 
    button: 
      lobby: 
        text: Lobby
        tip: Return t' th' game lobby
      play_again: 
        text: Again
        tip: Replay this level with th' same god an' buccaneers
      play_next: 
        text: Next
        tip: Play th' next level with th' same buccaneers
