--- 
back: &id003 
  text: Belay
instructions: &id004 
  text: Instructions
  tip: Learn how t' play th' game
options: &id005 
  text: Riggin'
  tip: View an' change game settings
cancel_button: &id002 
  text: Cancel
ok_button: &id001 
  text: OK
game: 
  title: "-=- Wrath: Appease or Die! -=- by Spooner -=-"
god: 
  ai: 
    name: SadOS
  azathoth: 
    name: Spawn o' Azathoth
  dryad: 
    name: Dryad
  earthquake: 
    name: Earthshaker
  mummy: 
    name: Muhazateptephotep
  squid: 
    name: Th' Kraken
  storm: 
    name: Poseidon
  volcano: 
    name: Th' Great Volcano
priest: 
  acolyte: 
    name: Acolyte
  chaplain: 
    name: Chaplain
  cutie: 
    name: Cutie
  druidess: 
    name: Druidess
  monk: 
    name: Monk
  nun: 
    name: Nun
  priestess: 
    name: Priestess
  prophet: 
    name: Prophet
  seer: 
    name: Seer
  shaman: 
    name: Shaman
  scientist: 
    name: Scientist
  thaumaturge: 
    name: Thaumaturge
  witch: 
    name: Witch
level: 
  cave: 
    name: Cave o' Considerable Doom
  desert: 
    name: Desert o' Dehydrated Doom
  facility: 
    name: D.O.O.M. Test Facility
  forest: 
    name: Forest o' Doom
  island: 
    name: Island o' Utter Doom
  moon: 
    name: Yuggoth
  ship: 
    name: Ship o' Doomed Fools
  undersea: 
    name: Davey Jones' Doom
gui: 
  view_achievements: 
    title: Deeds
    locked: Locked
    unlocked: Unlocked
    dialog: 
      confirm_reset: 
        message: Really delete all statistics, achivements an' unlocks?
        button: 
          ok: *id001
          cancel: *id002
    button: 
      back: *id003
      unlock: 
        text: Unlock all
        tip: Allow use o' all features, even if they be locked, until game be restarted
      reset: 
        text: Reset statistics
        tip: Resets all statistics, deeds an' unlocks PERMANENTLY
  game_menu: 
    button: 
      resume: 
        text: Resume
        tip: Resume playin' th' current game
      instructions: *id004
      options: *id005
      quit: 
        text: Quit
  host_details: 
    title: Hostin' a Game
    label: 
      player_name: Pirate name
      port: Port
    button: 
      back: *id003
      host: 
        text: Host
  instructions: 
    title: Instructions
    button: 
      back: *id003
      next: 
        text: Next
      previous: 
        text: Previous
    tab: 
      gods: 
        title: Th' Gods
        body: |
          * Gods ask for specific creatures, which will reap greater rewards when sacrificed.
          
          * Sacrificin' creatures that were not requested, will provide very little reward.

      anger: 
        title: Anger
        body: |
          * Gods slowly become angry then they rain down disasters until they become bored (bar fills then empties).
          
          * Each sacrifice reduces th' anger o' th' god as well as givin' favour.

      maps: 
        title: Maps
        body: |
          * Each realm has a local deity that ye must appease, such as th' god o' earthquakes or storms.
          
          * If all realms have been played, ye will be able t' pick any god in any realm.

      priests: 
        title: Buccaneers
        body: |
          * Each pirate picks one o' thirteen buccaneers, though not all will be unlocked initially.
          
          * All buccaneers be identical in play, but some look cooler than others.

      interaction: 
        title: Interaction
        body: |
          * Yer buccaneer can pick up, use or throw objects or creatures.
          
          * They do this with a single "action" key, which be context-sensitive.

      favour: 
        title: Favour
        body: |
          * Th' gods like animals, people an' treasures as sacrifices, but dislike mundane things, like rocks.
          
          * Favour can also be used t' power magical items.

      altar: 
        title: Th' Altar
        body: |
          * Creatures an' objects can be sacrificed at th' altar.
          
          * Accumulate favour by makin' sacrifices at th' altar.

      font: 
        title: Th' Font
        body: |
          * Creatures may be anointed at th' font t' give more favour when sacrificed.
          
          * Droppin' an anointed creature will remove th' blessin', but it can be re-anointed.

      winning: 
        title: Winnin'
        body: |
          * Yer holy favour be shown as a white bar. Fill th' bar afor th' other buccaneer t' win!
          
          * Yer health be shown as a red bar. Dyin' will mean th' other pirate wins by default!

      credits: 
        title: Credits
        body: |
          * Art, Sound & Code: Spooner
          
          * Music: Brian Peppers
          
          * Font: Copyright 1998-2003 Yuji Oshihoto
          
          * Some sprites an' th' overall graphical style: Oryx
          
          * Libraries (Ruby gems):
            - Gosu by jlnr
            - Chingu by Ippa
            - TexPlay by Banisterfiend
            - Fidgit by Spooner
            - Chipmunk
            - R18n
            - Ocra (for Windows executable)

  join_details: 
    title: Joinin' a Game
    label: 
      player_name: Pirate name
      address: Host address
      port: Host port
    button: 
      back: *id003
      join: 
        text: Join
  lobby: 
    title: 
      host: Host lobby
      client: Client lobby
      offline: Lobby
    button: 
      back: *id003
      send: 
        text: Send
      ready: 
        text: Ready
      start: 
        text: Start
    label: 
      god: God
      map: Map
      ready: Ready
      wait_for_start: Wait for host t' start game
  menu: 
    title: Wrath
    subtitle: Appease or Die!
    dialog: 
      confirm_quit: 
        message: Really leave?
        button: 
          ok: *id001
          cancel: *id002
    label: 
      version: v%1
    button: 
      play: 
        text: Play
        tip: Play th' game, on- or off-line
      instructions: *id004
      achievements: 
        text: Deeds
        tip: Review yer deeds
      options: *id005
      exit: 
        text: Exit
        tip: Leave game
  options: 
    title: Riggin'
    dialog: 
      confirm_default: 
        message: Really reset all riggin' (audio, video an' controls) t' their default values?
        button: 
          ok: *id001
          cancel: *id002
    button: 
      back: *id003
      audio: 
        text: Audio
      video: 
        text: Video
      controls: 
        text: Controls
      general: 
        text: General
      default: 
        text: Default all riggin'
        tip: Reset all riggin' (audio, video an' controls) t' their default values
  options_audio: 
    title: Riggin' | Audio
    dialog: 
      confirm_default: 
        message: Really set all volumes t' default values an' remove mutin'?
        button: 
          ok: *id001
          cancel: *id002
    label: 
      master: Master
      effects: Effects
      music: Music
    button: 
      back: *id003
      mute: 
        text: Mute
      play_sample: 
        text: Play
      play_song: 
        text: Play
      stop_song: 
        text: Stop
      default: 
        text: Defaults
        tip: Reset volumes t' default values an' remove mutin'
  options_general: 
    title: Riggin' | General
    default_locale: Default
    label: 
      locale: Locale
      warning: Changes require that th' game be restarted
    button: 
      back: *id003
  options_video: 
    title: Riggin' | Video
    zoom: (X%1 zoom)
    dialog: 
      confirm_default: 
        message: Really run th' game in a window at th' default size?
        button: 
          ok: *id001
          cancel: *id002
    label: 
      warning: Changes require that th' game be restarted
    button: 
      back: *id003
      windowed: 
        text: Windowed
        tip: Run th' game in a window
      full_screen: 
        text: Full-screen
        tip: Run th' game in a full screen at desktop resolution
      default: 
        text: Defaults
        tip: Reset t' default values
      exit: 
        text: Exit
  options_controls: 
    title: Riggin' | Controls
    dialog: 
      confirm_default: 
        message: Really default all controls?
        button: 
          ok: *id001
          cancel: *id002
    label: 
      up: Up
      down: Down
      left: Left
      right: Right
      action: Action
      toggle_network: Network stats (online)
      toggle_fps: FPS
      chat: Chat (online)
      menu: Menu
    button: 
      back: *id003
      default: 
        text: Defaults
        tip: Reset all controls t' their default values
    tab: 
      offline_player_1: 
        text: Pirate 1
        tip: Controls for pirate 1 (left side) when sharin' th' keyboard
      offline_player_2: 
        text: Pirate 2
        tip: Controls for pirate 2 (right side) when sharin' th' keyboard
      online_player: 
        text: Online pirate
        tip: Controls for th' pirate in a network game
      general: 
        text: General
        tip: General controls, such as diplayin' FPS or chattin' in network play.
  play: 
    title: Play Wrath
    button: 
      back: *id003
      offline: 
        text: Offline game
        tip: Both pirates on th' same keyboard
      join: 
        text: Join Game
        tip: Connect t' a network game someone else be hostin'
      host: 
        text: Host Game
        tip: Host a network game that another pirate can join
  game_over: 
    button: 
      lobby: 
        text: Lobby
        tip: Return t' th' game lobby
      play_again: 
        text: Again
        tip: Replay this level with th' same god an' buccaneers
      play_next: 
        text: Next
        tip: Play th' next level with th' same buccaneers
