---
# Aliases.
back: &back_button
  text: Back
instructions: &instructions_button
  text: Instructions
  tip: Learn how to play the game
options: &options_button
  text: Options
  tip: View and change game settings

# Game window.
game:
  title: "-=- Wrath: Appease or Die! -=- by Spooner -=-"

# Gods.
god:
  ai:
    name: SadOS
  azathoth:
    name: Spawn of Azathoth
  dryad:
    name: Dryad
  earthquake:
    name: Earthshaker
  mummy:
    name: Muhazateptephotep
  squid:
    name: The Kraken
  storm:
    name: Poseidon
  volcano:
    name: The Great Volcano

# Priests.
priest:
  acolyte:
    name: Acolyte
  chaplain:
    name: Chaplain
  cutie:
    name: Cutie
  druidess:
    name: Druidess
  monk:
    name: Monk
  nun:
    name: Nun
  priestess:
    name: Priestess
  prophet:
    name: Prophet
  seer:
    name: Seer
  shaman:
    name: Shaman
  scientist:
    name: Scientist
  thaumaturge:
    name: Thaumaturge
  witch:
    name: Witch

# Levels.
level:
  cave:
    name: Cave of Considerable Doom
  desert:
    name: Desert of Dehydrated Doom
  facility:
    name: D.O.O.M. Test Facility
  forest:
    name: Forest of Doom
  island:
    name: Island of Utter Doom
  moon:
    name: Yuggoth
  ship:
    name: Ship of Doomed Fools
  undersea:
    name: Davey Jones' Doom

# Gui screens.
gui:
  # View Achievements
  view_achievements:
    title: Achievements
    locked: Locked
    unlocked: Unlocked
    dialog:
      confirm_reset:
        message: Really delete all statistics, achivements and unlocks?
    button:
      back: *back_button
      unlock:
        text: Unlock all
        tip: Allow use of all features, even if they are locked, until game is restarted
      reset:
        text: Reset statistics
        tip: Resets all statistics, achievements and unlocks PERMANENTLY

  game_menu:
    button:
      resume:
        text: Resume
        tip: Resume playing the current game
      instructions: *instructions_button
      options: *options_button
      quit:
        text: Quit

  # Host details
  host_details:
    title: Hosting a Game

    label:
      player_name: Player name
      port: Port

    button:
      back: *back_button
      host:
        text: Host

  # Instructions
  instructions:
    title: Instructions
    button:
      back: *back_button
      next:
        text: Next
      previous:
        text: Previous

    tab:
      gods:
        title: The Gods
        body: |
          * Gods ask for specific creatures, which will reap greater rewards when sacrificed.

          * Sacrificing creatures that were not requested, will provide very little reward.

      anger:
        title: Anger
        body: |
          * Gods slowly become angry then they rain down disasters until they become bored (bar fills then empties).

          * Each sacrifice reduces the anger of the god as well as giving favour.

      maps:
        title: Maps
        body: |
          * Each realm has a local deity that you must appease, such as the god of earthquakes or storms.

          * If all realms have been played, you will be able to pick any god in any realm.

      priests:
        title: Priests
        body: |
          * Each player picks one of thirteen priests, though not all will be unlocked initially.

          * All priests are identical in play, but some look cooler than others.

      interaction:
        title: Interaction
        body: |
          * Your priest can pick up, use or throw objects or creatures.

          * They do this with a single "action" key, which is context-sensitive.

      favour:
        title: Favour
        body: |
          * The gods like animals, people and treasures as sacrifices, but dislike mundane things, like rocks.

          * Favour can also be used to power magical items.

      altar:
        title: The Altar
        body: |
          * Creatures and objects can be sacrificed at the altar.

          * Accumulate favour by making sacrifices at the altar.

      font:
        title: The Font
        body: |
          * Creatures may be anointed at the font to give more favour when sacrificed.

          * Dropping an anointed creature will remove the blessing, but it can be re-anointed.

      winning:
        title: Winning
        body: |
          * Your holy favour is shown as a white bar. Fill the bar before the other priest to win!

          * Your health is shown as a red bar. Dying will mean the other player wins by default!

      credits:
        title: Credits
        body: |
          * Art, Sound & Code: Spooner

          * Music: Brian Peppers

          * Font: Copyright 1998-2003 Yuji Oshihoto

          * Some sprites and the overall graphical style: Oryx

          * Libraries (Ruby gems):
            - Gosu by jlnr
            - Chingu by Ippa
            - TexPlay by Banisterfiend
            - Fidgit by Spooner
            - Chipmunk
            - R18n
            - Ocra (for Windows executable)

  # Join Details
  join_details:
    title: Joining a Game
    label:
      player_name: Player name
      address: Host address
      port: Host port

    button:
      back: *back_button
      join:
        text: Join

  # Lobby
  lobby:
    title:
      host: Host lobby
      client: Client lobby
      offline: Lobby

    button:
      back: *back_button
      send:
        text: Send
      ready:
        text: Ready
      start:
        text: Start

    label:
      god: God
      map: Map
      ready: Ready
      wait_for_start: Wait for host to start game

  # Main Menu
  menu:
    title: Wrath
    subtitle: Appease or Die!
    label:
      version: v%1

    button:
      play:
        text: Play
        tip: Play the game, on- or off-line
      instructions: *instructions_button
      achievements:
        text: Achievements
        tip: Review your achievements
      options: *options_button
      exit:
        text: Exit
        tip: Leave game

  # Options.
  options:
    title: Options
    dialog:
      confirm_default:
        message: Really reset all options (audio, video and controls) to their default values?
    button:
      back: *back_button
      audio:
        text: Audio
      video:
        text: Video
      controls:
        text: Controls
      general:
        text: General
      default:
        text: Default all options
        tip: Reset all options (audio, video and controls) to their default values

  # Options - Audio.
  options_audio:
    title: Options | Audio
    dialog:
      confirm_default:
        message: Really set all volumes to default values and remove muting?
    label:
      master: Master
      effects: Effects
      music: Music
    button:
      back: *back_button
      mute:
        text: Mute
      play_sample:
        text: Play
      play_song:
        text: Play
      stop_song:
        text: Stop
      default:
        text: Defaults
        tip: Reset volumes to default values and remove muting

  # Options - General.
  options_general:
    title: Options | General
    default_locale: Default
    label:
      locale: Locale
      warning: Changes require that the game be restarted
    button:
      back: *back_button

  # Options - Video.
  options_video:
    title: Options | Video
    zoom: (X%1 zoom)
    dialog:
      confirm_default:
        message: Really run the game in a window at the default size?
    label:
      warning: Changes require that the game be restarted
    button:
      back: *back_button
      windowed:
        text: Windowed
        tip: Run the game in a window
      full_screen:
        text: Full-screen
        tip: Run the game in a full screen at desktop resolution
      default:
        text: Defaults
        tip: Reset to default values
      exit:
        text: Exit

  # Options - Controls.
  options_controls:
    title: Options | Controls
    dialog:
      confirm_default:
        message: Really default all controls?
    label:
      up: Up
      down: Down
      left: Left
      right: Right
      action: Action
      toggle_network: Network stats (online)
      toggle_fps: FPS
      chat: Chat (online)
      menu: Menu

    button:
      back: *back_button
      default:
        text: Defaults
        tip: Reset all controls to their default values
    tab:
      offline_player_1:
        text: Player 1
        tip: Controls for player 1 (left side) when sharing the keyboard
      offline_player_2:
        text: Player 2
        tip: Controls for player 2 (right side) when sharing the keyboard
      online_player:
        text: Online player
        tip: Controls for the player in a network game
      general:
        text: General
        tip: General controls, such as diplaying FPS or chatting in network play.

  # Play
  play:
    title: Play Wrath

    button:
      back: *back_button
      offline:
        text: Offline game
        tip: Both players on the same keyboard
      join:
        text: Join Game
        tip: Connect to a network game someone else is hosting
      host:
        text: Host Game
        tip: Host a network game that another player can join

  # Game over
  game_over:
    button:
      lobby:
        text: Lobby
        tip: Return to the game lobby
      play_again:
        text: Again
        tip: Replay this level with the same god and priests
      play_next:
        text: Next
        tip: Play the next level with the same priests