--- 
achievement: 
  played_online: 
    title: Paranoid
    description: Play an online game, not lettin' anyone touch yer precious keyboard. Just have t' worry about th' alien mind-control lasers now!
  played_offline: 
    title: War o' elbows
    description: Play an offline game, in which thar should be lots o' frantic elbowin' action (bloody noses be goin' too far, though).
  long_play_1: 
    title: Waster o' time
    description: Play for an hour; time which ye won't e'er get belay.
  long_play_2: 
    title: Methuselah
    description: Play for 10 hours, which be very nearly a thousand years.
  played_forest: 
    title: Forester
    description: Play %1 with an eye t' rapid deforestation.
  played_cave: 
    title: Spelunker
    description: Play %1 in th' dark.
  played_island: 
    title: Castaway
    description: Play %1 with a friend who doesn't talk much.
  played_ship: 
    title: All in th' eye-liner
    description: Play %1 with a mockney accent an' a bit too much eye-makeup.
  played_undersea: 
    title: Aquamarina
    description: Play %1 with visible strin'.
  played_desert: 
    title: Sand got in th' sandwiches
    description: Play %1 without Tupperware.
  played_facility: 
    title: Tested
    description: Play %1 while bein' overseen by a benevolent AI.
  played_moon: 
    title: Cosmic Horror
    description: Play %1 without much sanity left.
  sacrificed_object: 
    title: Wrecker
    description: Sacrifice 100 inanimate objects.
  sacrificed_animal: 
    title: Animal sacrifice
    description: Sacrifice 10 defenceless animals.
  sacrificed_humanoid: 
    title: Th' sun will come up tomorrow
    description: Indulge in human(oid) sacrifice. Th' Aztecs swore by it!
  sacrificed_everything: 
    title: High Buccaneer
    description: Make 1000 sacrifices, just t' make sure!
  sacrificed_knight: 
    title: Knightmare
    description: Sacrifice a knight, who unlike brave Sir Robin, won't get t' run away.
  sacrificed_monkey: 
    title: Twelve Monkeys
    description: Sacrifice 12 monkeys.
  sacrificed_test_subject: 
    title: Slave t' th' Machine
    description: Sacrifice th' life o' th' innocent test subject for Science.
  sacrificed_sheep: 
    title: Butcher
    description: Sacrifice 100 sheep.
  death_fire: 
    title: Charcoal briquette
    description: Burn t' death.
  damage_1: 
    title: Black an' blue
    description: Take 10,000 damage.
  status_irradiated: 
    title: Nightlight
    description: Be irradiated for a minute.
unlock: 
  choose_god: 
    title: Religious freedom
  language_leet: 
    title: Talk like a n00b
  language_pirate: 
    title: Talk like a pirate
