--- 
achievement: 
  played_online: 
    title: Aranoidpay
    description: Ayedplay anway onlineway Amegay, Otnay Ettinglay anyoneway Ouchtay Myay Eciouspray Eyboardkay. Ustjay Avehay Otay Orryway aboutway Ethay alienway Indmay-Ontrolcay Aserslay Ownay!
  played_offline: 
    title: Arway ofway elbowsway
    description: Ayedplay anway offlineway Amegay, inway Ichwhay Erethay Ouldshay Avehay Eenbay Otslay ofway Anticfray elbowingway actionway.
  long_play_1: 
    title: Asterway ofway Imetay
    description: Ayedplay Orfay anway Ourhay; Imetay Ichwhay Onway't everway Ebay Otgay Ackbay.
  long_play_2: 
    title: Ethuselahmay
    description: Ayedplay Orfay 10way Ourshay, Ichwhay isway Eryvay Earlynay a Ousandthay Earsyay.
  played_forest: 
    title: Oresterfay
    description: Ayedplay Ethay Orestfay Evellay Ithway anway eyeway Otay Apidray Eforestationday.
  played_cave: 
    title: Elunkerspay
    description: Ayedplay Ethay Avecay Evellay inway Ethay Arkday.
  played_island: 
    title: Castaway
    description: Ayedplay Ethay Islandway Evellay Ithway a Iendfray Owhay Oesnday't Alktay Uchmay.
  played_ship: 
    title: Allway inway Ethay eyeway-Inerlay
    description: Ayedplay Ethay Ipshay Evellay Ithway a Ockneymay accentway andway a Itbay Ootay Uchmay eyeway-Akeupmay.
  played_undersea: 
    title: Aquamarinaway
    description: Ayedplay Ethay Underseaway Evellay Ithway Isiblevay Ingstray.
  played_desert: 
    title: Andsay Otgay inway Ethay Andwichessay
    description: Ayedplay Ethay Esertday Evellay Ithoutway Upperwaretay.
  played_facility: 
    title: Estedtay
    description: Ayedplay Ethay Acilityfay Evellay Ilewhay Eingbay overseenway Byay a Enevolentbay AIway.
  played_moon: 
    title: Osmiccay Orrorhay
    description: Ayedplay Ethay Uggothyay Evellay Ithoutway Uchmay Anitysay Eftlay.
  sacrificed_object: 
    title: Eckerwray
    description: Acrificedsay 100way inanimateway objectsway.
  sacrificed_animal: 
    title: Animalway Acrificesay
    description: Acrificedsay 10way Efencelessday animalsway.
  sacrificed_humanoid: 
    title: Ethay Unsay Illway Omecay upway Omorrowtay
    description: Indulgedway inway Umanhay(oidway) Acrificesay. Ethay Aztecsway Oresway Byay itway!
  sacrificed_everything: 
    title: Ighhay Iestpray
    description: Ademay 1000way Acrificessay, Ustjay Otay Akemay Uresay.
  sacrificed_knight: 
    title: Ightmareknay
    description: Acrificedsay Avebray Irsay Obinray, Owhay Idnday't Etgay Otay Unray away.
  sacrificed_monkey: 
    title: 12way Onkeysmay
    description: Acrificedsay Elvetway Onkeysmay.
  sacrificed_test_subject: 
    title: Aveslay Otay Ethay Achinemay
    description: Acrificedsay Ethay Ifelay ofway Ethay innocentway Esttay Ubjectsay Orfay Iencescay.
  sacrificed_sheep: 
    title: Utcherbay
    description: Acrificedsay 100way Eepshay.
  death_fire: 
    title: Arcoalchay Iquettebray
    description: Urnedbay Otay Eathday.
  damage_1: 
    title: Ackblay andway Ueblay
    description: Ooktay 10way,000way Amageday.
  status_irradiated: 
    title: Ightlightnay
    description: Irradiatedway Orfay a Inutemay.
