---
achievement:
  # ---------------------------------------
  # Number of times played and time played.
  # ---------------------------------------
  played_online:
    title: Paranoid
    description: Play an online game, not letting anyone touch your precious keyboard. Just have to worry about the alien mind-control lasers now!

  played_offline:
    title: War of elbows
    description: Play an offline game, in which there should be lots of frantic elbowing action (bloody noses is going too far, though).

  long_play_1:
    title: Waster of time
    description: Play for an hour; time which you won't ever get back.


  long_play_2:
    title: Methuselah
    description: Play for 10 hours, which is very nearly a thousand years.

  # ---------------------------------------
  # Number of times played each level.
  # ---------------------------------------
  played_forest:
    title: Forester
    description: Play %1 with an eye to rapid deforestation.

  played_cave:
    title: Spelunker
    description: Play %1 in the dark.

  played_island:
    title: Castaway
    description: Play %1 with a friend who doesn't talk much.

  played_ship:
    title: All in the eye-liner
    description: Play %1 with a mockney accent and a bit too much eye-makeup.

  played_undersea:
    title: Aquamarina
    description: Play %1 with visible string.

  played_desert:
    title: Sand got in the sandwiches
    description: Play %1 without Tupperware.

  played_facility:
    title: Tested
    description: Play %1 while being overseen by a benevolent AI.

  played_moon:
    title: Cosmic Horror
    description: Play %1 without much sanity left.
  # ---------------------------------------
  # Sacrifices (general).
  # ---------------------------------------
  sacrificed_object:
    title: Wrecker
    description: Sacrifice 100 inanimate objects.

  sacrificed_animal:
    title: Animal sacrifice
    description: Sacrifice 10 defenceless animals.

  sacrificed_humanoid:
    title: The sun will come up tomorrow
    description: Indulge in human(oid) sacrifice. The Aztecs swore by it!

  sacrificed_everything:
    title: High Priest
    description: Make 1000 sacrifices, just to make sure!

  # ---------------------------------------
  # Sacrifices (by type).
  # ---------------------------------------
  sacrificed_knight:
    title: Knightmare
    description: Sacrifice a knight, who unlike brave Sir Robin, won't get to run away.

  sacrificed_monkey:
    title: Twelve Monkeys
    description: Sacrifice 12 monkeys.

  sacrificed_test_subject:
    title: Slave to the Machine
    description: Sacrifice the life of the innocent test subject for Science.

  sacrificed_sheep:
    title: Butcher
    description: Sacrifice 100 sheep.

  # Deaths
  death_fire:
    title: Charcoal briquette
    description: Burn to death.

  # Damage levels.
  damage_1:
    title: Black and blue
    description: Take 10,000 damage.

  # Status effects.
  status_irradiated:
    title: Nightlight
    description: Be irradiated for a minute.

unlock:
  choose_god:
    title: Religious freedom

  language_leet:
    title: Talk like a n00b

  language_pirate:
    title: Talk like a pirate