---
# ---------------------------------------
# Number of times played and time played.
# ---------------------------------------
-
  :name: :played_online
  :statistics:
    - [:played, :online, :times]
  :required: 1
  :unlocks: []

-
  :name: :played_offline
  :statistics:
    - [:played, :offline, :times]
  :required: 1
  :unlocks: []

-
  :name: :long_play_1
  :statistics:
    - [:played, :offline, :duration]
    - [:played, :online, :duration]
  :required: 3600
  :unlocks:
    -
      :type: :priest
      :name: :chaplain

-
  :name: :long_play_2
  :statistics:
    - [:played, :offline, :duration]
    - [:played, :online, :duration]
  :required: 36000
  :unlocks: []


# ---------------------------------------
# Number of times played each level.
# ---------------------------------------
-
  :name: :played_forest
  :statistics:
    - [:levels, :Forest, :played]
  :required: 1
  :unlocks:
    -
      :type: :level
      :name: :Cave
    -
      :type: :priest
      :name: :druidess

-
  :name: :played_cave
  :statistics:
    - [:levels, :Cave, :played]
  :required: 1
  :unlocks:
    -
      :type: :level
      :name: :Island
    -
      :type: :priest
      :name: :thaumaturge

-
  :name: :played_island
  :statistics:
    - [:levels, :Island, :played]
  :required: 1
  :unlocks:
    -
      :type: :level
      :name: :Ship
    -
      :type: :priest
      :name: :seer

-
  :name: :played_ship
  :statistics:
    - [:levels, :Ship, :played]
  :required: 1
  :unlocks:
    -
      :type: :level
      :name: :Undersea
    -
      :type: :priest
      :name: :priestess
    -
      :type: :general
      :name: :language_pirate

-
  :name: :played_undersea
  :statistics:
    - [:levels, :Undersea, :played]
  :required: 1
  :unlocks:
    -
      :type: :level
      :name: :Desert
    -
      :type: :priest
      :name: :acolyte
      
-
  :name: :played_desert
  :statistics:
    - [:levels, :Desert, :played]
  :required: 1
  :unlocks:
    -
      :type: :level
      :name: :Facility
    -
      :type: :priest
      :name: :prophet

-
  :name: :played_facility
  :statistics:
    - [:levels, :Facility, :played]
  :required: 1
  :unlocks:
    -
      :type: :level
      :name: :Moon
    -
      :type: :priest
      :name: :cutie
    -
      :type: :general
      :name: :language_leet
       
-
  :name: :played_moon
  :statistics:
    - [:levels, :Moon, :played]
  :required: 1
  :unlocks:
    -
      :type: :priest
      :name: :shaman
    -
      :type: :general
      :name: :choose_god

# ---------------------------------------
# Sacrifices (general).
# ---------------------------------------
-
  :name: :sacrificed_object
  :statistics:
    - [:sacrifices, :totals, :objects]
  :required: 100
  :unlocks: []

-
  :name: :sacrificed_animal
  :statistics:
    - [:sacrifices, :totals, :animals]
  :required: 10
  :unlocks: []

-
  :name: :sacrificed_humanoid
  :statistics:
    - [:sacrifices, :totals, :humanoids]
  :required: 1
  :unlocks: []

-
  :name: :sacrificed_everything
  :statistics:
    - [:sacrifices, :totals, :objects]
    - [:sacrifices, :totals, :animals]
    - [:sacrifices, :totals, :humanoids]
  :required: 1000
  :unlocks:
    -
      :type: :priest
      :name: :nun

# ---------------------------------------
# Sacrifices (by type).
# ---------------------------------------
-
  :name: :sacrificed_knight
  :statistics:
    - [:sacrifices, :type, :Knight]
  :required: 1
  :unlocks: []

-
  :name: :sacrificed_monkey
  :statistics:
    - [:sacrifices, :type, :Monkey]
  :required: 12
  :unlocks: []

-
  :name: :sacrificed_test_subject
  :statistics:
    - [:sacrifices, :type, :TestSubject]
  :required: 1
  :unlocks:
    -
      :type: :priest
      :name: :scientist

-
  :name: :sacrificed_sheep
  :statistics:
    - [:sacrifices, :type, :Sheep]
  :required: 100
  :unlocks: []

# Deaths
-
  :name: :death_fire
  :statistics:
    - [:deaths, :type, :Fire]
  :required: 1
  :unlocks: []

# Damage
-
  :name: :damage_1
  :statistics:
    - [:damage, :total]
  :required: 10000
  :unlocks: []

# Status effects
-
  :name: :status_irradiated
  :statistics:
    - [:status, :irradiated]
  :required: 60.0
  :unlocks: []
